# This pipeline is started by 00_start.sh script. See header of 00_start.sh for additional information.

{
mkdir $1
echo starting script 01...
source 01_pheno_corr.sh $*
echo starting script 02...
Rscript 02_convert_long_to_wide_form.R $1
echo starting script 03...
source 03_gene_corr.sh $*
echo starting script 04...
Rscript 04_gene_corr_to_matrices.R $1
echo starting script 05...
Rscript 05_shared_heredity.R $1
} 2>&1 | tee $1/logs_01-05.txt
