# Aim of this script is to fuse tables obtained by grepping of clumped SNPs for original traits and Shared heredity GWAS

library(data.table)

setwd('/mnt/polyomica/projects/shared_heredity/data/03_neurodegenerative_diseases')

# Load files generated by grep in order to extract summary statistics for clumped SNPs

bip <- fread('./BIP/04_clumped_snps/bip_clumped_snps_only_v2.txt', header = F, stringsAsFactors = F)
mdd <- fread('./MDD/04_clumped_snps/mdd_clumped_snps_only_v2.txt', header = F, stringsAsFactors = F)
scz <- fread('./SCZ/04_clumped_snps/scz_clumped_snps_only_v2.txt', header = F, stringsAsFactors = F)
sh <- fread('./several_traits/linear_combination/04_clumped_snps/sh_clumped_snps_only_v2.txt', header = F, stringsAsFactors = F)

colnames(bip) <- colnames(mdd) <- colnames(scz) <- colnames(sh) <- c("gwas_id", "rs_id", "snp_num", "chr", "bp", "ea", "ra", "eaf", "af_ref", "beta", "se", "p", "n", "z", "info", "af_outlier", "pz_outlier", "p_gc")

# Load table with clumping results

clump <- fread('./several_traits/Clumping_for_all_orignal_traits_and_SH.txt')

# Reorder files for simplicity

# BIP
table(clump$rs_id == bip$rs_id)
table(clump$rs_id %in% bip$rs_id)
ind <- match(clump$rs_id, bip$rs_id)
bip <- bip[ind, ]

# MDD
table(clump$rs_id == mdd$rs_id)
table(clump$rs_id %in% mdd$rs_id)
ind <- match(clump$rs_id, mdd$rs_id)
mdd <- mdd[ind, ]

# SCZ
table(clump$rs_id == scz$rs_id)
table(clump$rs_id %in% scz$rs_id)
ind <- match(clump$rs_id, scz$rs_id)
scz <- scz[ind, ]

# SH
table(clump$rs_id == sh$rs_id)
table(clump$rs_id %in% sh$rs_id)
ind <- match(clump$rs_id, sh$rs_id)
sh <- sh[ind, ]

# Add extra columns to the table

clump$p_gc_bip <- bip$p_gc
clump$p_gc_mdd <- mdd$p_gc
clump$p_gc_scz <- scz$p_gc
clump$p_gc_sh <- sh$p_gc

clump$se_bip <- bip$se
clump$se_mdd <- mdd$se
clump$se_scz <- scz$se
clump$se_sh <- sh$se

clump$beta_bip <- bip$beta
clump$beta_mdd <- mdd$beta
clump$beta_scz <- scz$beta
clump$beta_sh <- sh$beta

fwrite(clump, './several_traits/clumping_extended.txt', sep = '\t', dec = '.')
